[package]
name = "rico8"
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]
description = "A Rust-like language that transpiles to Pico-8 Lua"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
insta = "1.34"
