-- Generated by Rico8
-- Pico-8 API functions are available natively

BUTTONS = {o = 4, x = 5}

COLORS = {black = 0, dark_blue = 1, dark_purple = 2, dark_green = 3, brown = 4, dark_grey = 5, light_grey = 6, white = 7, red = 8, orange = 9, yellow = 10, green = 11, blue = 12, lavender = 13, pink = 14, light_peach = 15}

-- struct SMap
SMap = {}

-- impl SMap
function SMap:new()
  local obj
  obj = {scroll = -128, scrolling = true}
  setmetatable(obj, {__index = SMap})
  return obj
end
function SMap:stop_scroll()
  self.scrolling = false
end
function SMap:update()
  if not self.scrolling   then
    return
  end
  local last_y = ((128 * 16) - 128)
  if (self.scroll >= last_y)   then
    self.scroll = -256
  end
  self.scroll = (self.scroll + 0.3)
end
function SMap:draw()
  cls(COLORS.dark_grey)
  for i=0,7   do
    local tile_x = (i * 16)
    local map_y = ((i * -256) + self.scroll)
    map(tile_x, 0, 0, map_y, 16, 32)
  end
end

-- trait Entity
Entity = {}
function Entity:draw(
)
  local sprite = self:get_sprite()
  local x = (flr(self:get_x()) + 0.5)
  local y = (flr(self:get_y()) + 0.5)
  spr(sprite.num, x, y, sprite.w, sprite.h)
end
function Entity:move_dir(
dir, speed)
  local x = self:get_x()
  local y = self:get_y()
  local __match = dir
  if __match.tag == "Left"   then
    self:set_x((x - speed))
  elseif __match.tag == "Right"   then
    self:set_x((x + speed))
  elseif __match.tag == "Up"   then
    self:set_y((y - speed))
  elseif __match.tag == "Down"   then
    self:set_y((y + speed))
  elseif __match.tag == "LeftUp"   then
    self:set_x((x - speed))
    self:set_y((y - speed))
  elseif __match.tag == "RightUp"   then
    self:set_x((x + speed))
    self:set_y((y - speed))
  elseif __match.tag == "LeftDown"   then
    self:set_x((x - speed))
    self:set_y((y + speed))
  elseif __match.tag == "RightDown"   then
    self:set_x((x + speed))
    self:set_y((y + speed))
    end
end
function Entity:collides_with(
other_x, other_y, other_size)
  local my_x = self:get_x()
  local my_y = self:get_y()
  local my_size = self:get_size()
  return ((((my_x < (other_x + other_size.w)) and ((my_x + my_size.w) > other_x)) and (my_y < (other_y + other_size.h))) and ((my_y + my_size.h) > other_y))
end
function Entity:is_enemy(
)
  local __match = self:get_type()
  if __match.tag == "Enemy"   then
    return true
  elseif true   then
    return false
    end
end
function Entity:is_player(
)
  local __match = self:get_type()
  if __match.tag == "Player"   then
    return true
  elseif true   then
    return false
    end
end

-- enum EntityType
Player = {
  tag = "Player"
}
Enemy = {
  tag = "Enemy"
}
Bullet = {
  tag = "Bullet"
}
Explosion = {
  tag = "Explosion"
}

-- struct Sprite
Sprite = {}

-- struct Size
Size = {}

-- enum Direction
Left = {
  tag = "Left"
}
Right = {
  tag = "Right"
}
Up = {
  tag = "Up"
}
Down = {
  tag = "Down"
}
LeftUp = {
  tag = "LeftUp"
}
RightUp = {
  tag = "RightUp"
}
LeftDown = {
  tag = "LeftDown"
}
RightDown = {
  tag = "RightDown"
}

-- struct Shooter
Shooter = {}

-- impl Shooter
function Shooter:new(props)
  local obj
  obj = {props = props, last_shot_time = 0}
  setmetatable(obj, {__index = Shooter})
  return obj
end
function Shooter:update(entity_x, entity_y)
  self.last_shot_time = (self.last_shot_time + 0.033)
end
function Shooter:can_shoot()
  return (self.last_shot_time >= self.props.interval)
end
function Shooter:shoot()
  if self:can_shoot()   then
    self.last_shot_time = 0
  end
end
function Shooter:get_bullet_spawn_x(entity_x)
  return (entity_x + self.props.x_offset)
end
function Shooter:get_bullet_spawn_y(entity_y)
  return (entity_y + self.props.y_offset)
end

-- struct BulletProps
BulletProps = {}

-- struct Rotor
Rotor = {}

-- impl Rotor
function Rotor:new(props)
  local obj
  obj = {props = props, angle = 0, entity_x = 0, entity_y = 0}
  setmetatable(obj, {__index = Rotor})
  return obj
end
function Rotor:update(entity_x, entity_y)
  self.entity_x = entity_x
  self.entity_y = entity_y
  self.angle = (self.angle + 0.4)
  if (self.angle > 6.28)   then
    self.angle = (self.angle - 6.28)
  end
end
function Rotor:draw()
  local center_x = (self.entity_x + self.props.x)
  local center_y = (self.entity_y + self.props.y)
  local dx = (cos(self.angle) * self.props.length)
  local dy = (sin(self.angle) * self.props.length)
  line((center_x - dx), (center_y - dy), (center_x + dx), (center_y + dy), 6)
  if (self.props.length > 1.5)   then
    local angle2 = (self.angle + 1.57)
    local dx2 = (cos(angle2) * self.props.length)
    local dy2 = (sin(angle2) * self.props.length)
    line((center_x - dx2), (center_y - dy2), (center_x + dx2), (center_y + dy2), 6)
  end
end

-- struct RotorProps
RotorProps = {}

-- enum Scene
Start = {
  tag = "Start"
}
Game = {
  tag = "Game"
}
GameOver = {
  tag = "GameOver"
}

-- struct TheLady
TheLady = {}

-- impl TheLady
function TheLady:new()
  local obj
local bullet_props = {x_offset = 0, y_offset = -1, interval = 0.4, sw = 1, sh = 1}
  obj = {x = 63, y = 111, sprite = {num = 1, w = 1, h = 1}, size = {w = 8, h = 8}, shooter = Shooter:new(bullet_props), main_rotor = Rotor:new({x = 4.5, y = 3.5, length = 2}), tail_rotor = Rotor:new({x = 4, y = 7, length = 1}), alive = true}
  setmetatable(obj, {__index = TheLady})
  return obj
end
function TheLady:update(scene)
  local is_game = (function()
    local __match = scene
    if __match.tag == "Game"     then
      return true
    elseif true     then
      return false
        end
  end)()
  local outside = (is_game and self:move_player() or false)
  self.shooter:update(self.x, self.y)
  self.main_rotor:update(self.x, self.y)
  self.tail_rotor:update(self.x, self.y)
  return outside
end
function TheLady:draw()
  if self.alive   then
    palt(256)
    local x = (flr(self.x) + 0.5)
    local y = (flr(self.y) + 0.5)
    spr(self.sprite.num, x, y, self.sprite.w, self.sprite.h)
    palt(32768)
    self.main_rotor:draw()
    self.tail_rotor:draw()
  end
end
function TheLady:move_player()
  local can_l = (self.x > -1)
  local can_r = ((self.x + self.size.w) < 126)
  local can_u = (self.y > 0)
  local can_d = ((self.y + self.size.h) < 128)
  local can_lu = (can_l and can_u)
  local can_ld = (can_l and can_d)
  local can_ru = (can_r and can_u)
  local can_rd = (can_r and can_d)
  local direction = nil
  local should_move = false
  if ((btn(0) and btn(2)) and can_lu)   then
    direction = LeftUp
    should_move = true
  else
    if ((btn(1) and btn(2)) and can_ru)     then
      direction = RightUp
      should_move = true
    else
      if ((btn(0) and btn(3)) and can_ld)       then
        direction = LeftDown
        should_move = true
      else
        if ((btn(1) and btn(3)) and can_rd)         then
          direction = RightDown
          should_move = true
        else
          if (btn(0) and can_l)           then
            direction = Left
            should_move = true
          else
            if (btn(1) and can_r)             then
              direction = Right
              should_move = true
            else
              if (btn(2) and can_u)               then
                direction = Up
                should_move = true
              else
                if (btn(3) and can_d)                 then
                  direction = Down
                  should_move = true
                end
              end
            end
          end
        end
      end
    end
  end
  if should_move   then
    self:move_dir(direction, 1)
  end
  return ((((self.x < -10) or (self.x > 138)) or (self.y < -10)) or (self.y > 138))
end
function TheLady:get_x()
  return self.x
end
function TheLady:get_y()
  return self.y
end
function TheLady:hit()
  self.alive = false
  sfx(1)
end
function TheLady:is_alive()
  return self.alive
end

-- impl Entity for TheLady
function TheLady:get_x()
  return self.x
end
function TheLady:get_y()
  return self.y
end
function TheLady:set_x(x)
  self.x = x
end
function TheLady:set_y(y)
  self.y = y
end
function TheLady:get_sprite()
  return self.sprite
end
function TheLady:get_size()
  return self.size
end
function TheLady:get_type()
  return Player
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if TheLady[k] == nil then
    TheLady[k] = v
  end
end

-- struct EnemyAircraft
EnemyAircraft = {}

-- impl EnemyAircraft
function EnemyAircraft:new()
  local obj
local x = flr(rnd(127))
local bullet_props = {x_offset = 3, y_offset = 4, interval = 1, sw = 1, sh = 1}
  obj = {x = x, y = -8, sprite = {num = 32, w = 1, h = 1}, size = {w = 6, h = 8}, shooter = Shooter:new(bullet_props), main_rotor = Rotor:new({x = 2.5, y = 4, length = 2}), tail_rotor = Rotor:new({x = 2, y = 0, length = 1}), alive = true}
  setmetatable(obj, {__index = EnemyAircraft})
  return obj
end
function EnemyAircraft:update(scene, airwolf_x)
  if not self.alive   then
    return true
  end
  local is_game = (function()
    local __match = scene
    if __match.tag == "Game"     then
      return true
    elseif true     then
      return false
        end
  end)()
  local outside = (is_game and self:move_enemy(airwolf_x) or false)
  self.shooter:update(self.x, self.y)
  self.main_rotor:update(self.x, self.y)
  self.tail_rotor:update(self.x, self.y)
  return outside
end
function EnemyAircraft:draw()
  if self.alive   then
    local x = (flr(self.x) + 0.5)
    local y = (flr(self.y) + 0.5)
    spr(self.sprite.num, x, y, self.sprite.w, self.sprite.h)
    self.main_rotor:draw()
    self.tail_rotor:draw()
  end
end
function EnemyAircraft:move_enemy(airwolf_x)
  if (self.x < airwolf_x)   then
    self.x = (self.x + 0.5)
    self.y = (self.y + 0.3)
  else
    if (self.x > airwolf_x)     then
      self.x = (self.x - 0.5)
      self.y = (self.y + 0.3)
    else
      self.y = (self.y + 0.5)
    end
  end
  if (rnd(100) < 2)   then
  end
  return (self.y > 140)
end
function EnemyAircraft:hit()
  self.alive = false
end
function EnemyAircraft:is_alive()
  return self.alive
end
function EnemyAircraft:should_shoot()
  return self.shooter:can_shoot()
end
function EnemyAircraft:did_shoot()
  self.shooter:shoot()
end
function EnemyAircraft:get_x()
  return self.x
end
function EnemyAircraft:get_y()
  return self.y
end
function EnemyAircraft:get_size()
  return self.size
end

-- impl Entity for EnemyAircraft
function EnemyAircraft:get_x()
  return self.x
end
function EnemyAircraft:get_y()
  return self.y
end
function EnemyAircraft:set_x(x)
  self.x = x
end
function EnemyAircraft:set_y(y)
  self.y = y
end
function EnemyAircraft:get_sprite()
  return self.sprite
end
function EnemyAircraft:get_size()
  return self.size
end
function EnemyAircraft:get_type()
  return Enemy
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if EnemyAircraft[k] == nil then
    EnemyAircraft[k] = v
  end
end

-- struct Bullet
Bullet = {}

-- impl Bullet
function Bullet:new(x, y, velx, vely)
  local obj
  obj = {x = x, y = y, velx = velx, vely = vely, sprite = {num = 64, w = 1, h = 1}, size = {w = 6, h = 8}, is_enemy = false}
  setmetatable(obj, {__index = Bullet})
  return obj
end
function Bullet:new_enemy(x, y, velx, vely)
  local obj
  obj = {x = x, y = y, velx = velx, vely = vely, sprite = {num = 65, w = 1, h = 1}, size = {w = 1, h = 6}, is_enemy = true}
  setmetatable(obj, {__index = Bullet})
  return obj
end
function Bullet:update()
  self.x = (self.x + self.velx)
  self.y = (self.y + self.vely)
  return ((((self.x < -8) or (self.x > 136)) or (self.y < -8)) or (self.y > 136))
end
function Bullet:is_enemy_bullet()
  return self.is_enemy
end

-- impl Entity for Bullet
function Bullet:get_x()
  return self.x
end
function Bullet:get_y()
  return self.y
end
function Bullet:set_x(x)
  self.x = x
end
function Bullet:set_y(y)
  self.y = y
end
function Bullet:get_sprite()
  return self.sprite
end
function Bullet:get_size()
  return self.size
end
function Bullet:get_type()
  return Bullet
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if Bullet[k] == nil then
    Bullet[k] = v
  end
end

-- struct Explosion
Explosion = {}

-- impl Explosion
function Explosion:new(x, y)
  local obj
  obj = {x = x, y = y, sprite = {num = 0, w = 1, h = 1}, size = {w = 1, h = 1}, active = true, timer = 30}
  setmetatable(obj, {__index = Explosion})
  return obj
end
function Explosion:update()
  if not self.active   then
    return true
  end
  self.timer = (self.timer - 1)
  if (self.timer <= 0)   then
    self.active = false
    return true
  end
  return false
end
function Explosion:get_x()
  return self.x
end
function Explosion:get_y()
  return self.y
end

-- impl Entity for Explosion
function Explosion:get_x()
  return self.x
end
function Explosion:get_y()
  return self.y
end
function Explosion:set_x(x)
  self.x = x
end
function Explosion:set_y(y)
  self.y = y
end
function Explosion:get_sprite()
  return self.sprite
end
function Explosion:get_size()
  return self.size
end
function Explosion:get_type()
  return Explosion
end
function Explosion:draw()
  if self.active   then
    local x = self.x
    local y = self.y
    local r = (self.timer / 5)
    if (r > 0)     then
      circfill(x, y, r, COLORS.light_grey)
      circ(x, y, (r + 1), COLORS.dark_grey)
    end
    for i=0,3     do
      local angle = (i * 90)
      local dist = (8 - (self.timer / 4))
      if (dist > 0)       then
        pset((x + dist), y, COLORS.yellow)
        pset((x - dist), y, COLORS.yellow)
        pset(x, (y + dist), COLORS.yellow)
        pset(x, (y - dist), COLORS.yellow)
      end
    end
  end
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if Explosion[k] == nil then
    Explosion[k] = v
  end
end

-- enum UpdateResult
function Score(...)
  local args = {...}
  return {
    tag = "Score",
    _0 = args[1],
  }
end
PlayerDied = {
  tag = "PlayerDied"
}

-- struct Entities
Entities = {}

-- impl Entities
function Entities:new()
  local obj
  obj = {player = TheLady:new(), enemies = {}, bullets = {}, explosions = {}, enemy_spawn_timer = 0}
  setmetatable(obj, {__index = Entities})
  return obj
end
function Entities:update(scene, score)
  local new_score = score
  self.player:update(scene)
  local i = count(self.explosions)
  while (i > 0)   do
    i = (i - 1)
    local explosion = self.explosions[(i + 1)]
    local should_remove = explosion:update()
    if should_remove     then
      deli(self.explosions, (i + 1))
    end
  end
  if not self.player:is_alive()   then
    return PlayerDied
  end
  local is_game = (function()
    local __match = scene
    if __match.tag == "Game"     then
      return true
    elseif true     then
      return false
        end
  end)()
  if not is_game   then
    return Score(new_score)
  end
  self.enemy_spawn_timer = (self.enemy_spawn_timer + 1)
  if (self.enemy_spawn_timer > 90)   then
    self:spawn_enemy()
    self.enemy_spawn_timer = 0
  end
  local player_x = self.player:get_x()
  local i = 0
  while (i < count(self.enemies))   do
    local enemy = self.enemies[(i + 1)]
    local should_remove = enemy:update(scene, player_x)
    if ((is_game and enemy:is_alive()) and enemy:should_shoot())     then
      self:add_enemy_bullet((enemy:get_x() + 3), (enemy:get_y() + 4))
      enemy:did_shoot()
    end
    if ((not should_remove and self.player:is_alive()) and self.player:collides_with(enemy:get_x(), enemy:get_y(), enemy:get_size()))     then
      self:add_explosion(enemy:get_x(), enemy:get_y())
      self:add_explosion(self.player:get_x(), self.player:get_y())
      enemy:hit()
      self.player:hit()
      should_remove = true
    end
    if should_remove     then
      if enemy:is_alive()       then
        new_score = (new_score + 20)
      else
        new_score = (new_score + 10)
        if not self.player:collides_with(enemy:get_x(), enemy:get_y(), enemy:get_size())         then
          self:add_explosion(enemy:get_x(), enemy:get_y())
        end
      end
      deli(self.enemies, (i + 1))
    else
      i = (i + 1)
    end
  end
  i = 0
  while (i < count(self.bullets))   do
    local bullet = self.bullets[(i + 1)]
    local should_remove = bullet:update()
    local hit_something = false
    if not should_remove     then
      if bullet:is_enemy_bullet()       then
        if (self.player:is_alive() and bullet:collides_with(self.player:get_x(), self.player:get_y(), self.player:get_size()))         then
          self.player:hit()
          self:add_explosion(self.player:get_x(), self.player:get_y())
          hit_something = true
        end
      else
        for _,enemy in pairs(self.enemies)         do
          if (enemy:is_alive() and bullet:collides_with(enemy:get_x(), enemy:get_y(), enemy:get_size()))           then
            enemy:hit()
            self:add_explosion(enemy:get_x(), enemy:get_y())
            new_score = (new_score + 10)
            hit_something = true
            break
          end
        end
      end
    end
    if (should_remove or hit_something)     then
      deli(self.bullets, (i + 1))
    else
      i = (i + 1)
    end
  end
  if (btnp(4, 0) or btnp(5, 0))   then
    self:add_bullet((self.player:get_x() + 3), (self.player:get_y() - 2), 0, -2)
  end
  return Score(new_score)
end
function Entities:draw()
  self.player:draw()
  for _,enemy in pairs(self.enemies)   do
    enemy:draw()
  end
  for _,bullet in pairs(self.bullets)   do
    bullet:draw()
  end
  for _,explosion in pairs(self.explosions)   do
    explosion:draw()
  end
end
function Entities:spawn_enemy()
  local enemy = EnemyAircraft:new()
  add(self.enemies, enemy)
end
function Entities:add_bullet(x, y, velx, vely)
  local bullet = Bullet:new(x, y, velx, vely)
  add(self.bullets, bullet)
  sfx(0)
end
function Entities:add_enemy_bullet(x, y)
  local bullet = Bullet:new_enemy(x, y, 0, 2)
  add(self.bullets, bullet)
  sfx(0)
end
function Entities:add_explosion(x, y)
  local explosion = Explosion:new(x, y)
  add(self.explosions, explosion)
  sfx(1)
end
function Entities:get_player()
  return self.player
end
function Entities:get_enemy_count()
  return count(self.enemies)
end
function Entities:get_bullet_count()
  return count(self.bullets)
end

-- struct GameState
GameState = {}

game = nil

function _init()
  poke(24374, 2)
  game = {smap = SMap:new(), entities = Entities:new(), scene = Start, score = 0, go_timer = 90, hscore = 0, start_timer = 0}
end

function _update60()
  game.smap:update()
  local update_result = game.entities:update(game.scene, game.score)
  local __match = update_result
  if __match.tag == "PlayerDied"   then
    local is_game_scene = (function()
      local __match = game.scene
      if __match.tag == "Game"       then
        return true
      elseif true       then
        return false
            end
    end)()
    if is_game_scene     then
      game_over()
    end
  elseif __match.tag == "Score"   then
    local score = __match._0
    game.score = score
    end
  local __match = game.scene
  if __match.tag == "Start"   then
    if btnp(BUTTONS.o, 0)     then
      start_game()
    end
  elseif __match.tag == "Game"   then
    game.start_timer = (game.start_timer + 1)
    if (game.start_timer > 900)     then
      music(-1, 5000, 0)
    end
  elseif __match.tag == "GameOver"   then
    game.go_timer = (game.go_timer - 1)
    if (game.go_timer <= 0)     then
      if btnp(BUTTONS.o, 0)       then
        start_game()
      end
    end
    end
end

function _draw()
  game.smap:draw()
  game.entities:draw()
  local __match = game.scene
  if __match.tag == "Start"   then
    print("AIRWOLF", 48, 50, COLORS.yellow)
    print("press o to start", 30, 70, COLORS.white)
  elseif __match.tag == "Game"   then
    print(("SCORE: " .. tostr(game.score, false)), 2, 2, COLORS.white)
  elseif __match.tag == "GameOver"   then
    print("game over", 44, 60, COLORS.white)
    print(("SCORE: " .. tostr(game.score, false)), 36, 70, COLORS.yellow)
    if (game.go_timer <= 0)     then
      print("press o to restart", 26, 80, COLORS.white)
    end
    end
end

function start_game()
  game.scene = Game
  game.score = 0
  game.entities = Entities:new()
  game.smap = SMap:new()
  game.start_timer = 0
  music(0, -1, 7)
end

function game_over()
  game.scene = GameOver
  game.go_timer = 90
  music(-1, 100, 0)
  if (game.score > game.hscore)   then
    game.hscore = game.score
  end
end

