-- Generated by Rico8
-- Pico-8 API functions are available natively

-- trait Entity
Entity = {}
-- Default implementation for Entity:draw
-- Default implementation for Entity:move_dir
-- Default implementation for Entity:collides_with
-- Default implementation for Entity:is_enemy
-- Default implementation for Entity:is_player

-- struct Sprite
Sprite = {}

-- struct Size
Size = {}

-- struct Bullet
Bullet = {}

-- impl Bullet
function Bullet:new(x, y, velx, vely)
  local obj
  obj = {x = x, y = y, velx = velx, vely = vely, sprite = {num = 16, w = 1, h = 1}, size = {w = 2, h = 2}}
  setmetatable(obj, {__index = Bullet})
  return obj
end
function Bullet:update()
  self.x = (self.x + self.velx)
  self.y = (self.y + self.vely)
  return ((((self.x < -8) or (self.x > 136)) or (self.y < -8)) or (self.y > 136))
end

-- impl Entity for Bullet
function Bullet:get_x()
  return self.x
end
function Bullet:get_y()
  return self.y
end
function Bullet:set_x(x)
  self.x = x
end
function Bullet:set_y(y)
  self.y = y
end
function Bullet:get_sprite()
  return self.sprite
end
function Bullet:get_size()
  return self.size
end
function Bullet:get_type()
  return 2
end

