-- Generated by Rico8
-- Pico-8 API functions are available natively

PI = 3.1415927

-- struct ButtonMasks
ButtonMasks = {}

BUTTON_MASKS = {left = 1, right = 2, up = 4, down = 8, left_up = 5, right_up = 6, left_down = 9, right_down = 10}

-- struct Buttons
Buttons = {}

BUTTONS = {o = 4, x = 5}

-- struct Colors
Colors = {}

COLORS = {black = 0, dark_blue = 1, dark_purple = 2, dark_green = 3, brown = 4, dark_grey = 5, light_grey = 6, white = 7, red = 8, orange = 9, yellow = 10, green = 11, blue = 12, lavender = 13, pink = 14, light_peach = 15}

