-- Generated by Rico8
-- Pico-8 API functions are available natively

-- trait Entity
Entity = {}

function Entity:draw(
)
  local sprite = self:get_sprite()
  local x = (flr(self:get_x()) + 0.5)
  local y = (flr(self:get_y()) + 0.5)
  spr(sprite.num, x, y, sprite.w, sprite.h)
end
function Entity:collides_with(
other_x, other_y, other_size)
  local my_x = self:get_x()
  local my_y = self:get_y()
  local my_size = self:get_size()
  return ((((my_x < (other_x + other_size.w)) and ((my_x + my_size.w) > other_x)) and (my_y < (other_y + other_size.h))) and ((my_y + my_size.h) > other_y))
end

-- struct Sprite
Sprite = {}

-- struct Size
Size = {}

-- struct Shooter
Shooter = {}

-- impl Shooter
function Shooter:new(props)
  local obj
  obj = {props = props, last_shot_time = 0}
  setmetatable(obj, {__index = Shooter})
  return obj
end
function Shooter:update(entity_x, entity_y)
  self.last_shot_time = (self.last_shot_time + 0.033)
end
function Shooter:can_shoot()
  return (self.last_shot_time >= self.props.interval)
end
function Shooter:shoot()
  if self:can_shoot()   then
    self.last_shot_time = 0
  end
end
function Shooter:get_bullet_spawn_x(entity_x)
  return (entity_x + self.props.x_offset)
end
function Shooter:get_bullet_spawn_y(entity_y)
  return (entity_y + self.props.y_offset)
end

-- struct BulletProps
BulletProps = {}

-- struct Rotor
Rotor = {}

-- impl Rotor
function Rotor:new(props)
  local obj
  obj = {props = props, angle = 0, entity_x = 0, entity_y = 0}
  setmetatable(obj, {__index = Rotor})
  return obj
end
function Rotor:update(entity_x, entity_y)
  self.entity_x = entity_x
  self.entity_y = entity_y
  self.angle = (self.angle + 0.4)
  if (self.angle > 6.28)   then
    self.angle = (self.angle - 6.28)
  end
end
function Rotor:draw()
  local center_x = (self.entity_x + self.props.x)
  local center_y = (self.entity_y + self.props.y)
  local dx = (cos(self.angle) * self.props.length)
  local dy = (sin(self.angle) * self.props.length)
  line((center_x - dx), (center_y - dy), (center_x + dx), (center_y + dy), 6)
  if (self.props.length > 1.5)   then
    local angle2 = (self.angle + 1.57)
    local dx2 = (cos(angle2) * self.props.length)
    local dy2 = (sin(angle2) * self.props.length)
    line((center_x - dx2), (center_y - dy2), (center_x + dx2), (center_y + dy2), 6)
  end
end

-- struct RotorProps
RotorProps = {}

-- enum Scene
Start = {
  tag = "Start"
}
Game = {
  tag = "Game"
}
GameOver = {
  tag = "GameOver"
}

-- struct EnemyAircraft
EnemyAircraft = {}

-- impl EnemyAircraft
function EnemyAircraft:new()
  local obj
local x = flr(rnd(127))
local bullet_props = {x_offset = 3, y_offset = 4, interval = 1, sw = 1, sh = 1}
  obj = {x = x, y = -8, sprite = {num = 32, w = 1, h = 1}, size = {w = 6, h = 8}, shooter = Shooter:new(bullet_props), main_rotor = Rotor:new({x = 2.5, y = 4, length = 2}), tail_rotor = Rotor:new({x = 2, y = 0, length = 1}), alive = true}
  setmetatable(obj, {__index = EnemyAircraft})
  return obj
end
function EnemyAircraft:update(scene, airwolf_x)
  if not self.alive   then
    return true
  end
  local is_game = (function()
    local __match = scene
    if __match.tag == "Game"     then
      return true
    elseif true     then
      return false
        end
  end)()
  local outside = (is_game and self:move_enemy(airwolf_x) or false)
  self.shooter:update(self.x, self.y)
  self.main_rotor:update(self.x, self.y)
  self.tail_rotor:update(self.x, self.y)
  return outside
end
function EnemyAircraft:move_enemy(airwolf_x)
  if (self.x < airwolf_x)   then
    self.x = (self.x + 0.5)
    self.y = (self.y + 0.3)
  else
    if (self.x > airwolf_x)     then
      self.x = (self.x - 0.5)
      self.y = (self.y + 0.3)
    else
      self.y = (self.y + 0.5)
    end
  end
  return (self.y > 140)
end
function EnemyAircraft:hit()
  self.alive = false
end
function EnemyAircraft:is_alive()
  return self.alive
end
function EnemyAircraft:should_shoot()
  return self.shooter:can_shoot()
end
function EnemyAircraft:did_shoot()
  self.shooter:shoot()
end
function EnemyAircraft:get_x()
  return self.x
end
function EnemyAircraft:get_y()
  return self.y
end
function EnemyAircraft:get_size()
  return self.size
end
function EnemyAircraft:should_shoot()
  return (self.shooter:can_shoot() and (rnd(100) < 2))
end
function EnemyAircraft:did_shoot()
  self.shooter:shoot()
end

-- impl Entity for EnemyAircraft
function EnemyAircraft:get_x()
  return self.x
end
function EnemyAircraft:get_y()
  return self.y
end
function EnemyAircraft:get_sprite()
  return self.sprite
end
function EnemyAircraft:get_size()
  return self.size
end
function EnemyAircraft:draw()
  if self.alive   then
    local x = (flr(self.x) + 0.5)
    local y = (flr(self.y) + 0.5)
    spr(self.sprite.num, x, y, self.sprite.w, self.sprite.h)
    self.main_rotor:draw()
    self.tail_rotor:draw()
  end
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if EnemyAircraft[k] == nil then
    EnemyAircraft[k] = v
  end
end

