-- Generated by Rico8
-- Pico-8 API functions are available natively

-- struct Sprite
Sprite = {}

-- struct Size
Size = {}

-- trait Entity
Entity = {}

function Entity:draw(
)
  local sprite = self:get_sprite()
  local x = (flr(self:get_x()) + 0.5)
  local y = (flr(self:get_y()) + 0.5)
  spr(sprite.num, x, y, sprite.w, sprite.h)
end
function Entity:collides_with(
other_x, other_y, other_size)
  local my_x = self:get_x()
  local my_y = self:get_y()
  local my_size = self:get_size()
  return ((((my_x < (other_x + other_size.w)) and ((my_x + my_size.w) > other_x)) and (my_y < (other_y + other_size.h))) and ((my_y + my_size.h) > other_y))
end

