-- Generated by Rico8
-- Pico-8 API functions are available natively

-- trait Entity
Entity = {}

function Entity:draw(
)
  local sprite = self:get_sprite()
  local x = (flr(self:get_x()) + 0.5)
  local y = (flr(self:get_y()) + 0.5)
  spr(sprite.num, x, y, sprite.w, sprite.h)
end
function Entity:collides_with(
other_x, other_y, other_size)
  local my_x = self:get_x()
  local my_y = self:get_y()
  local my_size = self:get_size()
  return ((((my_x < (other_x + other_size.w)) and ((my_x + my_size.w) > other_x)) and (my_y < (other_y + other_size.h))) and ((my_y + my_size.h) > other_y))
end

-- struct Sprite
Sprite = {}

-- struct Size
Size = {}

-- struct Shooter
Shooter = {}

-- impl Shooter
function Shooter:new(props)
  local obj
  obj = {props = props, last_shot_time = 0}
  setmetatable(obj, {__index = Shooter})
  return obj
end
function Shooter:update(entity_x, entity_y)
  self.last_shot_time = (self.last_shot_time + 0.033)
end
function Shooter:can_shoot()
  return (self.last_shot_time >= self.props.interval)
end
function Shooter:shoot()
  if self:can_shoot()   then
    self.last_shot_time = 0
  end
end
function Shooter:get_bullet_spawn_x(entity_x)
  return (entity_x + self.props.x_offset)
end
function Shooter:get_bullet_spawn_y(entity_y)
  return (entity_y + self.props.y_offset)
end

-- struct BulletProps
BulletProps = {}

-- struct Rotor
Rotor = {}

-- impl Rotor
function Rotor:new(props)
  local obj
  obj = {props = props, angle = 0, entity_x = 0, entity_y = 0}
  setmetatable(obj, {__index = Rotor})
  return obj
end
function Rotor:update(entity_x, entity_y)
  self.entity_x = entity_x
  self.entity_y = entity_y
  self.angle = (self.angle + 0.4)
  if (self.angle > 6.28)   then
    self.angle = (self.angle - 6.28)
  end
end
function Rotor:draw()
  local center_x = (self.entity_x + self.props.x)
  local center_y = (self.entity_y + self.props.y)
  local dx = (cos(self.angle) * self.props.length)
  local dy = (sin(self.angle) * self.props.length)
  line((center_x - dx), (center_y - dy), (center_x + dx), (center_y + dy), 6)
  if (self.props.length > 1.5)   then
    local angle2 = (self.angle + 1.57)
    local dx2 = (cos(angle2) * self.props.length)
    local dy2 = (sin(angle2) * self.props.length)
    line((center_x - dx2), (center_y - dy2), (center_x + dx2), (center_y + dy2), 6)
  end
end

-- struct RotorProps
RotorProps = {}

BUTTON_MASKS = {left = 1, right = 2, up = 4, down = 8, left_up = 5, right_up = 6, left_down = 9, right_down = 10}

-- enum Scene
Start = {
  tag = "Start"
}
Game = {
  tag = "Game"
}
GameOver = {
  tag = "GameOver"
}

-- struct TheLady
TheLady = {}

-- impl TheLady
function TheLady:new()
  local obj
local bullet_props = {x_offset = 0, y_offset = -1, interval = 0.4, sw = 1, sh = 1}
  obj = {x = 63, y = 111, sprite = {num = 1, w = 1, h = 1}, size = {w = 8, h = 8}, shooter = Shooter:new(bullet_props), main_rotor = Rotor:new({x = 4.5, y = 3.5, length = 2}), tail_rotor = Rotor:new({x = 4, y = 7, length = 1}), alive = true}
  setmetatable(obj, {__index = TheLady})
  return obj
end
function TheLady:update(scene)
  local is_game = (function()
    local __match = scene
    if __match.tag == "Game"     then
      return true
    elseif true     then
      return false
        end
  end)()
  local outside = (is_game and self:move_player() or false)
  self.shooter:update(self.x, self.y)
  self.main_rotor:update(self.x, self.y)
  self.tail_rotor:update(self.x, self.y)
  return outside
end
function TheLady:move_player()
  local can_l = (self.x > -1)
  local can_r = ((self.x + self.size.w) < 126)
  local can_u = (self.y > 0)
  local can_d = ((self.y + self.size.h) < 128)
  local can_lu = (can_l and can_u)
  local can_ld = (can_l and can_d)
  local can_ru = (can_r and can_u)
  local can_rd = (can_r and can_d)
  if ((btn(0) and btn(2)) and can_lu)   then
    self.x = (self.x - 1)
    self.y = (self.y - 1)
  else
    if ((btn(1) and btn(2)) and can_ru)     then
      self.x = (self.x + 1)
      self.y = (self.y - 1)
    else
      if ((btn(0) and btn(3)) and can_ld)       then
        self.x = (self.x - 1)
        self.y = (self.y + 1)
      else
        if ((btn(1) and btn(3)) and can_rd)         then
          self.x = (self.x + 1)
          self.y = (self.y + 1)
        else
          if (btn(0) and can_l)           then
            self.x = (self.x - 1)
          else
            if (btn(1) and can_r)             then
              self.x = (self.x + 1)
            else
              if (btn(2) and can_u)               then
                self.y = (self.y - 1)
              else
                if (btn(3) and can_d)                 then
                  self.y = (self.y + 1)
                end
              end
            end
          end
        end
      end
    end
  end
  return ((((self.x < -10) or (self.x > 138)) or (self.y < -10)) or (self.y > 138))
end
function TheLady:get_x()
  return self.x
end
function TheLady:get_y()
  return self.y
end
function TheLady:hit()
  self.alive = false
  sfx(1)
end
function TheLady:is_alive()
  return self.alive
end
function TheLady:get_size()
  return self.size
end

-- impl Entity for TheLady
function TheLady:get_x()
  return self.x
end
function TheLady:get_y()
  return self.y
end
function TheLady:get_sprite()
  return self.sprite
end
function TheLady:get_size()
  return self.size
end
function TheLady:draw()
  if self.alive   then
    palt(256)
    local x = (flr(self.x) + 0.5)
    local y = (flr(self.y) + 0.5)
    spr(self.sprite.num, x, y, self.sprite.w, self.sprite.h)
    palt(32768)
    self.main_rotor:draw()
    self.tail_rotor:draw()
  end
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if TheLady[k] == nil then
    TheLady[k] = v
  end
end

-- struct EnemyAircraft
EnemyAircraft = {}

-- impl EnemyAircraft
function EnemyAircraft:new()
  local obj
local x = flr(rnd(127))
local bullet_props = {x_offset = 3, y_offset = 4, interval = 1, sw = 1, sh = 1}
  obj = {x = x, y = -8, sprite = {num = 32, w = 1, h = 1}, size = {w = 6, h = 8}, shooter = Shooter:new(bullet_props), main_rotor = Rotor:new({x = 2.5, y = 4, length = 2}), tail_rotor = Rotor:new({x = 2, y = 0, length = 1}), alive = true}
  setmetatable(obj, {__index = EnemyAircraft})
  return obj
end
function EnemyAircraft:update(scene, airwolf_x)
  if not self.alive   then
    return true
  end
  local is_game = (function()
    local __match = scene
    if __match.tag == "Game"     then
      return true
    elseif true     then
      return false
        end
  end)()
  local outside = (is_game and self:move_enemy(airwolf_x) or false)
  self.shooter:update(self.x, self.y)
  self.main_rotor:update(self.x, self.y)
  self.tail_rotor:update(self.x, self.y)
  return outside
end
function EnemyAircraft:move_enemy(airwolf_x)
  if (self.x < airwolf_x)   then
    self.x = (self.x + 0.5)
    self.y = (self.y + 0.3)
  else
    if (self.x > airwolf_x)     then
      self.x = (self.x - 0.5)
      self.y = (self.y + 0.3)
    else
      self.y = (self.y + 0.5)
    end
  end
  return (self.y > 140)
end
function EnemyAircraft:hit()
  self.alive = false
end
function EnemyAircraft:is_alive()
  return self.alive
end
function EnemyAircraft:should_shoot()
  return self.shooter:can_shoot()
end
function EnemyAircraft:did_shoot()
  self.shooter:shoot()
end
function EnemyAircraft:get_x()
  return self.x
end
function EnemyAircraft:get_y()
  return self.y
end
function EnemyAircraft:get_size()
  return self.size
end
function EnemyAircraft:should_shoot()
  return (self.shooter:can_shoot() and (rnd(100) < 2))
end
function EnemyAircraft:did_shoot()
  self.shooter:shoot()
end

-- impl Entity for EnemyAircraft
function EnemyAircraft:get_x()
  return self.x
end
function EnemyAircraft:get_y()
  return self.y
end
function EnemyAircraft:get_sprite()
  return self.sprite
end
function EnemyAircraft:get_size()
  return self.size
end
function EnemyAircraft:draw()
  if self.alive   then
    local x = (flr(self.x) + 0.5)
    local y = (flr(self.y) + 0.5)
    spr(self.sprite.num, x, y, self.sprite.w, self.sprite.h)
    self.main_rotor:draw()
    self.tail_rotor:draw()
  end
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if EnemyAircraft[k] == nil then
    EnemyAircraft[k] = v
  end
end

-- struct Bullet
Bullet = {}

-- impl Bullet
function Bullet:new(x, y, velx, vely)
  local obj
  obj = {x = x, y = y, velx = velx, vely = vely, sprite = {num = 64, w = 1, h = 1}, size = {w = 6, h = 8}, is_enemy = false}
  setmetatable(obj, {__index = Bullet})
  return obj
end
function Bullet:new_enemy(x, y, velx, vely)
  local obj
  obj = {x = x, y = y, velx = velx, vely = vely, sprite = {num = 65, w = 1, h = 1}, size = {w = 1, h = 6}, is_enemy = true}
  setmetatable(obj, {__index = Bullet})
  return obj
end
function Bullet:update()
  self.x = (self.x + self.velx)
  self.y = (self.y + self.vely)
  return ((((self.x < -8) or (self.x > 136)) or (self.y < -8)) or (self.y > 136))
end
function Bullet:is_enemy_bullet()
  return self.is_enemy
end
function Bullet:hit()
end

-- impl Entity for Bullet
function Bullet:get_x()
  return self.x
end
function Bullet:get_y()
  return self.y
end
function Bullet:get_sprite()
  return self.sprite
end
function Bullet:get_size()
  return self.size
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if Bullet[k] == nil then
    Bullet[k] = v
  end
end

-- struct Explosion
Explosion = {}

-- impl Explosion
function Explosion:new(x, y)
  local obj
  obj = {x = x, y = y, sprite = {num = 0, w = 1, h = 1}, size = {w = 1, h = 1}, active = true, timer = 30}
  setmetatable(obj, {__index = Explosion})
  return obj
end
function Explosion:update()
  if not self.active   then
    return true
  end
  self.timer = (self.timer - 1)
  if (self.timer <= 0)   then
    self.active = false
    return true
  end
  return false
end
function Explosion:get_x()
  return self.x
end
function Explosion:get_y()
  return self.y
end

-- impl Entity for Explosion
function Explosion:get_x()
  return self.x
end
function Explosion:get_y()
  return self.y
end
function Explosion:get_sprite()
  return self.sprite
end
function Explosion:get_size()
  return self.size
end
function Explosion:draw()
  if self.active   then
    local x = self.x
    local y = self.y
    local r = (self.timer / 5)
    if (r > 0)     then
      circfill(x, y, r, 6)
      circ(x, y, (r + 1), 5)
    end
    for i=0,3     do
      local angle = (i * 90)
      local dist = (8 - (self.timer / 4))
      if (dist > 0)       then
        pset((x + dist), y, 10)
        pset((x - dist), y, 10)
        pset(x, (y + dist), 10)
        pset(x, (y - dist), 10)
      end
    end
  end
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if Explosion[k] == nil then
    Explosion[k] = v
  end
end

-- enum UpdateResult
function Score(...)
  local args = {...}
  return {
    tag = "Score",
    _0 = args[1],
  }
end
PlayerDied = {
  tag = "PlayerDied"
}

-- struct Entities
Entities = {}

-- impl Entities
function Entities:new()
  local obj
  obj = {player = TheLady:new(), enemies = {}, bullets = {}, explosions = {}, enemy_spawn_timer = 0}
  setmetatable(obj, {__index = Entities})
  return obj
end
function Entities:update(scene, score)
  local new_score = score
  self.player:update(scene)
  if not self.player:is_alive()   then
    return PlayerDied
  end
  local is_game = (function()
    local __match = scene
    if __match.tag == "Game"     then
      return true
    elseif true     then
      return false
        end
  end)()
  if not is_game   then
    return Score(new_score)
  end
  self.enemy_spawn_timer = (self.enemy_spawn_timer + 1)
  if (self.enemy_spawn_timer > 90)   then
    add(self.enemies, EnemyAircraft:new())
    self.enemy_spawn_timer = 0
  end
  local player_x = self.player:get_x()
  local i = count(self.enemies)
  while (i > 0)   do
    i = (i - 1)
    local should_remove = self.enemies[(i + 1)]:update(scene, player_x)
    if self.enemies[(i + 1)]:should_shoot()     then
      local ex = self.enemies[(i + 1)]:get_x()
      local ey = self.enemies[(i + 1)]:get_y()
      add(self.bullets, Bullet:new_enemy((ex + 3), (ey + 4), 0, 2))
      self.enemies[(i + 1)]:did_shoot()
      sfx(0)
    end
    if should_remove     then
      if not self.enemies[(i + 1)]:is_alive()       then
        self:add_explosion(self.enemies[(i + 1)]:get_x(), self.enemies[(i + 1)]:get_y())
        new_score = (new_score + 100)
      end
      deli(self.enemies, (i + 1))
    end
  end
  i = count(self.bullets)
  while (i > 0)   do
    i = (i - 1)
    if self.bullets[(i + 1)]:update()     then
      deli(self.bullets, (i + 1))
    end
  end
  i = count(self.explosions)
  while (i > 0)   do
    i = (i - 1)
    if self.explosions[(i + 1)]:update()     then
      deli(self.explosions, (i + 1))
    end
  end
  if (btnp(4) or btnp(5))   then
    local px = self.player:get_x()
    local py = self.player:get_y()
    add(self.bullets, Bullet:new((px + 3), (py - 2), 0, -2))
    sfx(0)
  end
  new_score = self:check_collisions(new_score)
  return Score(new_score)
end
function Entities:draw()
  self.player:draw()
  for _,enemy in pairs(self.enemies)   do
    enemy:draw()
  end
  for _,bullet in pairs(self.bullets)   do
    bullet:draw()
  end
  for _,explosion in pairs(self.explosions)   do
    explosion:draw()
  end
end
function Entities:add_explosion(x, y)
  add(self.explosions, Explosion:new(x, y))
  sfx(1)
end
function Entities:check_collisions(score)
  local new_score = score
  for i=0,(count(self.bullets) - 1)   do
    if self.bullets[(i + 1)]:is_enemy_bullet()     then
      if self.bullets[(i + 1)]:collides_with(self.player:get_x(), self.player:get_y(), self.player:get_size())       then
        self.player:hit()
        self.bullets[(i + 1)]:hit()
      end
    else
      for j=0,(count(self.enemies) - 1)       do
        if self.bullets[(i + 1)]:collides_with(self.enemies[(j + 1)]:get_x(), self.enemies[(j + 1)]:get_y(), self.enemies[(j + 1)]:get_size())         then
          self.enemies[(j + 1)]:hit()
          self.bullets[(i + 1)]:hit()
          new_score = (new_score + 10)
        end
      end
    end
  end
  for i=0,(count(self.enemies) - 1)   do
    if (self.enemies[(i + 1)]:is_alive() and self.enemies[(i + 1)]:collides_with(self.player:get_x(), self.player:get_y(), self.player:get_size()))     then
      self.player:hit()
      self.enemies[(i + 1)]:hit()
    end
  end
  return new_score
end

