-- Generated by Rico8
-- Pico-8 API functions are available natively

-- trait Entity
Entity = {}
-- Default implementation for Entity:draw
-- Default implementation for Entity:move_dir
-- Default implementation for Entity:collides_with
-- Default implementation for Entity:is_enemy
-- Default implementation for Entity:is_player

-- struct Sprite
Sprite = {}

-- struct Size
Size = {}

-- struct Shooter
Shooter = {}

-- impl Shooter
function Shooter:new(props)
  local obj
  obj = {props = props, last_shot_time = 0}
  setmetatable(obj, {__index = Shooter})
  return obj
end
function Shooter:update(entity_x, entity_y)
  self.last_shot_time = (self.last_shot_time + 0.033)
end
function Shooter:can_shoot()
  return (self.last_shot_time >= self.props.interval)
end
function Shooter:shoot()
  if self:can_shoot()   then
    self.last_shot_time = 0
  end
end
function Shooter:get_bullet_spawn_x(entity_x)
  return (entity_x + self.props.x_offset)
end
function Shooter:get_bullet_spawn_y(entity_y)
  return (entity_y + self.props.y_offset)
end

-- struct BulletProps
BulletProps = {}

-- struct Rotor
Rotor = {}

-- impl Rotor
function Rotor:new(props)
  local obj
  obj = {props = props, angle = 0, entity_x = 0, entity_y = 0}
  setmetatable(obj, {__index = Rotor})
  return obj
end
function Rotor:update(entity_x, entity_y)
  self.entity_x = entity_x
  self.entity_y = entity_y
  self.angle = (self.angle + 0.4)
  if (self.angle > 6.28)   then
    self.angle = (self.angle - 6.28)
  end
end
function Rotor:draw()
  local center_x = (self.entity_x + self.props.x)
  local center_y = (self.entity_y + self.props.y)
  local dx = (cos(self.angle) * self.props.length)
  local dy = (sin(self.angle) * self.props.length)
  line((center_x - dx), (center_y - dy), (center_x + dx), (center_y + dy), 6)
  if (self.props.length > 1.5)   then
    local angle2 = (self.angle + 1.57)
    local dx2 = (cos(angle2) * self.props.length)
    local dy2 = (sin(angle2) * self.props.length)
    line((center_x - dx2), (center_y - dy2), (center_x + dx2), (center_y + dy2), 6)
  end
end

-- struct RotorProps
RotorProps = {}

BUTTON_MASKS = {left = 1, right = 2, up = 4, down = 8, left_up = 5, right_up = 6, left_down = 9, right_down = 10}

-- struct TheLady
TheLady = {}

-- impl TheLady
function TheLady:new()
  local obj
local bullet_props = {x_offset = 0, y_offset = -1, interval = 0.4, sw = 1, sh = 1}
  obj = {x = 63, y = 111, sprite = {num = 1, w = 1, h = 1}, size = {w = 8, h = 8}, shooter = Shooter:new(bullet_props), main_rotor = Rotor:new({x = 4.5, y = 3.5, length = 2}), tail_rotor = Rotor:new({x = 4, y = 7, length = 1})}
  setmetatable(obj, {__index = TheLady})
  return obj
end
function TheLady:update(scene)
  local outside = ((scene == 1) and self:move_player() or false)
  self.shooter:update(self.x, self.y)
  self.main_rotor:update(self.x, self.y)
  self.tail_rotor:update(self.x, self.y)
  return outside
end
function TheLady:draw()
  palt(256)
  local x = (flr(self.x) + 0.5)
  local y = (flr(self.y) + 0.5)
  spr(self.sprite.num, x, y, self.sprite.w, self.sprite.h)
  palt(32768)
  self.main_rotor:draw()
  self.tail_rotor:draw()
end
function TheLady:move_player()
  local can_l = (self.x > -1)
  local can_r = ((self.x + self.size.w) < 126)
  local can_u = (self.y > 0)
  local can_d = ((self.y + self.size.h) < 128)
  local can_lu = (can_l and can_u)
  local can_ld = (can_l and can_d)
  local can_ru = (can_r and can_u)
  local can_rd = (can_r and can_d)
  if ((btn(0) and btn(2)) and can_lu)   then
    self.x = (self.x - 1)
    self.y = (self.y - 1)
  else
    if ((btn(1) and btn(2)) and can_ru)     then
      self.x = (self.x + 1)
      self.y = (self.y - 1)
    else
      if ((btn(0) and btn(3)) and can_ld)       then
        self.x = (self.x - 1)
        self.y = (self.y + 1)
      else
        if ((btn(1) and btn(3)) and can_rd)         then
          self.x = (self.x + 1)
          self.y = (self.y + 1)
        else
          if (btn(0) and can_l)           then
            self.x = (self.x - 1)
          else
            if (btn(1) and can_r)             then
              self.x = (self.x + 1)
            else
              if (btn(2) and can_u)               then
                self.y = (self.y - 1)
              else
                if (btn(3) and can_d)                 then
                  self.y = (self.y + 1)
                end
              end
            end
          end
        end
      end
    end
  end
  return ((((self.x < -10) or (self.x > 138)) or (self.y < -10)) or (self.y > 138))
end
function TheLady:get_x()
  return self.x
end
function TheLady:get_y()
  return self.y
end

-- impl Entity for TheLady
function TheLady:get_x()
  return self.x
end
function TheLady:get_y()
  return self.y
end
function TheLady:set_x(x)
  self.x = x
end
function TheLady:set_y(y)
  self.y = y
end
function TheLady:get_sprite()
  return self.sprite
end
function TheLady:get_size()
  return self.size
end
function TheLady:get_type()
  return 0
end

-- struct EnemyAircraft
EnemyAircraft = {}

-- impl EnemyAircraft
function EnemyAircraft:new()
  local obj
local x = flr(rnd(127))
local bullet_props = {x_offset = 3, y_offset = 4, interval = 1, sw = 1, sh = 1}
  obj = {x = x, y = -8, sprite = {num = 32, w = 1, h = 1}, size = {w = 6, h = 8}, shooter = Shooter:new(bullet_props), main_rotor = Rotor:new({x = 2.5, y = 4, length = 2}), tail_rotor = Rotor:new({x = 2, y = 0, length = 1}), alive = true}
  setmetatable(obj, {__index = EnemyAircraft})
  return obj
end
function EnemyAircraft:update(scene, airwolf_x)
  if not self.alive   then
    return true
  end
  local outside = ((scene == 1) and self:move_enemy(airwolf_x) or false)
  self.shooter:update(self.x, self.y)
  self.main_rotor:update(self.x, self.y)
  self.tail_rotor:update(self.x, self.y)
  return outside
end
function EnemyAircraft:draw()
  if self.alive   then
    local x = (flr(self.x) + 0.5)
    local y = (flr(self.y) + 0.5)
    spr(self.sprite.num, x, y, self.sprite.w, self.sprite.h)
    self.main_rotor:draw()
    self.tail_rotor:draw()
  end
end
function EnemyAircraft:move_enemy(airwolf_x)
  if (self.x < airwolf_x)   then
    self.x = (self.x + 0.5)
    self.y = (self.y + 0.3)
  else
    if (self.x > airwolf_x)     then
      self.x = (self.x - 0.5)
      self.y = (self.y + 0.3)
    else
      self.y = (self.y + 0.5)
    end
  end
  if (rnd(100) < 2)   then
  end
  return (self.y > 140)
end
function EnemyAircraft:hit()
  self.alive = false
end
function EnemyAircraft:is_alive()
  return self.alive
end
function EnemyAircraft:get_x()
  return self.x
end
function EnemyAircraft:get_y()
  return self.y
end
function EnemyAircraft:get_size()
  return self.size
end

-- impl Entity for EnemyAircraft
function EnemyAircraft:get_x()
  return self.x
end
function EnemyAircraft:get_y()
  return self.y
end
function EnemyAircraft:set_x(x)
  self.x = x
end
function EnemyAircraft:set_y(y)
  self.y = y
end
function EnemyAircraft:get_sprite()
  return self.sprite
end
function EnemyAircraft:get_size()
  return self.size
end
function EnemyAircraft:get_type()
  return 1
end

-- struct Bullet
Bullet = {}

-- impl Bullet
function Bullet:new(x, y, velx, vely)
  local obj
  obj = {x = x, y = y, velx = velx, vely = vely, sprite = {num = 16, w = 1, h = 1}, size = {w = 2, h = 2}}
  setmetatable(obj, {__index = Bullet})
  return obj
end
function Bullet:update()
  self.x = (self.x + self.velx)
  self.y = (self.y + self.vely)
  return ((((self.x < -8) or (self.x > 136)) or (self.y < -8)) or (self.y > 136))
end

-- impl Entity for Bullet
function Bullet:get_x()
  return self.x
end
function Bullet:get_y()
  return self.y
end
function Bullet:set_x(x)
  self.x = x
end
function Bullet:set_y(y)
  self.y = y
end
function Bullet:get_sprite()
  return self.sprite
end
function Bullet:get_size()
  return self.size
end
function Bullet:get_type()
  return 2
end

-- struct Explosion
Explosion = {}

-- impl Explosion
function Explosion:new(x, y)
  local obj
local sprite = {num = 0, w = 1, h = 1}
local size = {w = 1, h = 1}
local entity = Entity:new(x, y, sprite, 3, size)
  obj = {entity = entity, active = true, timer = 30}
  setmetatable(obj, {__index = Explosion})
  return obj
end
function Explosion:update()
  if not self.active   then
    return true
  end
  self.timer = (self.timer - 1)
  if (self.timer <= 0)   then
    self.active = false
    return true
  end
  return false
end
function Explosion:draw()
  if self.active   then
    local x = self.entity.x
    local y = self.entity.y
    local r = (self.timer / 5)
    if (r > 0)     then
      circfill(x, y, r, COLORS.light_grey)
      circ(x, y, (r + 1), COLORS.dark_grey)
    end
    for i=0,4     do
      local angle = (i * 90)
      local dist = (8 - (self.timer / 4))
      if (dist > 0)       then
        pset((x + dist), y, COLORS.yellow)
        pset((x - dist), y, COLORS.yellow)
        pset(x, (y + dist), COLORS.yellow)
        pset(x, (y - dist), COLORS.yellow)
      end
    end
  end
end
function Explosion:get_entity()
  return self.entity
end

enemies = {}

bullets = {}

explosions = {}

-- struct Entities
Entities = {}

-- impl Entities
function Entities:new()
  local obj
enemies = {}
bullets = {}
explosions = {}
  obj = {player = TheLady:new(), enemy_spawn_timer = 0}
  setmetatable(obj, {__index = Entities})
  return obj
end
function Entities:update(scene, score)
  local new_score = score
  self.player:update(scene)
  if (scene ~= 1)   then
    return new_score
  end
  self.enemy_spawn_timer = (self.enemy_spawn_timer + 1)
  if (self.enemy_spawn_timer > 90)   then
    self:spawn_enemy()
    self.enemy_spawn_timer = 0
  end
  local player_x = self.player:get_x()
  for i=0,count(enemies)   do
    local enemy = enemies[i]
    if enemy:update(scene, player_x)     then
      if not enemy:is_alive()       then
        self:add_explosion(enemy:get_x(), enemy:get_y())
      end
      del(enemies, i)
    end
  end
  for i=0,count(bullets)   do
    local bullet = bullets[i]
    if bullet:update()     then
      del(bullets, i)
    else
      for j=0,count(enemies)       do
        local enemy = enemies[j]
        if bullet:collides_with(enemy:get_x(), enemy:get_y(), enemy:get_size())         then
          enemy:hit()
          del(bullets, i)
          break
        end
      end
    end
  end
  for i=0,count(explosions)   do
    local explosion = explosions[i]
    if explosion:update()     then
      del(explosions, i)
    end
  end
  if (btnp(4, 0) or btnp(5, 0))   then
    self:add_bullet((self.player:get_x() + 3), (self.player:get_y() - 2), 0, -2)
  end
  return new_score
end
function Entities:draw()
  self.player:draw()
  for _,enemy in pairs(enemies)   do
    enemy:draw()
  end
  for _,bullet in pairs(bullets)   do
    bullet:draw()
  end
  for _,explosion in pairs(explosions)   do
    explosion:draw()
  end
end
function Entities:spawn_enemy()
  local enemy = EnemyAircraft:new()
  add(enemies, enemy)
end
function Entities:add_bullet(x, y, velx, vely)
  local bullet = Bullet:new(x, y, velx, vely)
  add(bullets, bullet)
  sfx(0)
end
function Entities:add_explosion(x, y)
  local explosion = Explosion:new(x, y)
  add(explosions, explosion)
  sfx(1)
end
function Entities:get_player()
  return self.player
end

