-- Generated by Rico8
-- Pico-8 API functions are available natively

-- trait Entity
Entity = {}

function Entity:draw(
)
  local sprite = self:get_sprite()
  local x = (flr(self:get_x()) + 0.5)
  local y = (flr(self:get_y()) + 0.5)
  spr(sprite.num, x, y, sprite.w, sprite.h)
end
function Entity:collides_with(
other_x, other_y, other_size)
  local my_x = self:get_x()
  local my_y = self:get_y()
  local my_size = self:get_size()
  return ((((my_x < (other_x + other_size.w)) and ((my_x + my_size.w) > other_x)) and (my_y < (other_y + other_size.h))) and ((my_y + my_size.h) > other_y))
end

-- struct Sprite
Sprite = {}

-- struct Size
Size = {}

COLORS = {black = 0, dark_blue = 1, dark_purple = 2, dark_green = 3, brown = 4, dark_grey = 5, light_grey = 6, white = 7, red = 8, orange = 9, yellow = 10, green = 11, blue = 12, lavender = 13, pink = 14, light_peach = 15}

-- struct Explosion
Explosion = {}

-- impl Explosion
function Explosion:new(x, y)
  local obj
  obj = {x = x, y = y, sprite = {num = 0, w = 1, h = 1}, size = {w = 1, h = 1}, active = true, timer = 30}
  setmetatable(obj, {__index = Explosion})
  return obj
end
function Explosion:update()
  if not self.active   then
    return true
  end
  self.timer = (self.timer - 1)
  if (self.timer <= 0)   then
    self.active = false
    return true
  end
  return false
end
function Explosion:get_x()
  return self.x
end
function Explosion:get_y()
  return self.y
end

-- impl Entity for Explosion
function Explosion:get_x()
  return self.x
end
function Explosion:get_y()
  return self.y
end
function Explosion:get_sprite()
  return self.sprite
end
function Explosion:get_size()
  return self.size
end
function Explosion:draw()
  if self.active   then
    local x = self.x
    local y = self.y
    local r = (self.timer / 5)
    if (r > 0)     then
      circfill(x, y, r, 6)
      circ(x, y, (r + 1), 5)
    end
    for i=0,3     do
      local angle = (i * 90)
      local dist = (8 - (self.timer / 4))
      if (dist > 0)       then
        pset((x + dist), y, 10)
        pset((x - dist), y, 10)
        pset(x, (y + dist), 10)
        pset(x, (y - dist), 10)
      end
    end
  end
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if Explosion[k] == nil then
    Explosion[k] = v
  end
end

