-- Generated by Rico8
-- Pico-8 API functions are available natively

-- trait Entity
Entity = {}
-- Default implementation for Entity:draw
-- Default implementation for Entity:move_dir
-- Default implementation for Entity:collides_with
-- Default implementation for Entity:is_enemy
-- Default implementation for Entity:is_player

-- struct Sprite
Sprite = {}

-- struct Size
Size = {}

COLORS = {black = 0, dark_blue = 1, dark_purple = 2, dark_green = 3, brown = 4, dark_grey = 5, light_grey = 6, white = 7, red = 8, orange = 9, yellow = 10, green = 11, blue = 12, lavender = 13, pink = 14, light_peach = 15}

-- struct Explosion
Explosion = {}

-- impl Explosion
function Explosion:new(x, y)
  local obj
local sprite = {num = 0, w = 1, h = 1}
local size = {w = 1, h = 1}
local entity = Entity:new(x, y, sprite, 3, size)
  obj = {entity = entity, active = true, timer = 30}
  setmetatable(obj, {__index = Explosion})
  return obj
end
function Explosion:update()
  if not self.active   then
    return true
  end
  self.timer = (self.timer - 1)
  if (self.timer <= 0)   then
    self.active = false
    return true
  end
  return false
end
function Explosion:draw()
  if self.active   then
    local x = self.entity.x
    local y = self.entity.y
    local r = (self.timer / 5)
    if (r > 0)     then
      circfill(x, y, r, COLORS.light_grey)
      circ(x, y, (r + 1), COLORS.dark_grey)
    end
    for i=0,4     do
      local angle = (i * 90)
      local dist = (8 - (self.timer / 4))
      if (dist > 0)       then
        pset((x + dist), y, COLORS.yellow)
        pset((x - dist), y, COLORS.yellow)
        pset(x, (y + dist), COLORS.yellow)
        pset(x, (y - dist), COLORS.yellow)
      end
    end
  end
end
function Explosion:get_entity()
  return self.entity
end

