-- Generated by Rico8
-- Pico-8 API functions are available natively

-- struct RotorProps
RotorProps = {}

-- struct Rotor
Rotor = {}

-- impl Rotor
function Rotor:new(props)
  local obj
  obj = {props = props, angle = 0, entity_x = 0, entity_y = 0}
  setmetatable(obj, {__index = Rotor})
  return obj
end
function Rotor:update(entity_x, entity_y)
  self.entity_x = entity_x
  self.entity_y = entity_y
  self.angle = (self.angle + 0.4)
  if (self.angle > 6.28)   then
    self.angle = (self.angle - 6.28)
  end
end
function Rotor:draw()
  local center_x = (self.entity_x + self.props.x)
  local center_y = (self.entity_y + self.props.y)
  local dx = (cos(self.angle) * self.props.length)
  local dy = (sin(self.angle) * self.props.length)
  line((center_x - dx), (center_y - dy), (center_x + dx), (center_y + dy), 6)
  if (self.props.length > 1.5)   then
    local angle2 = (self.angle + 1.57)
    local dx2 = (cos(angle2) * self.props.length)
    local dy2 = (sin(angle2) * self.props.length)
    line((center_x - dx2), (center_y - dy2), (center_x + dx2), (center_y + dy2), 6)
  end
end

