-- Generated by Rico8
-- Pico-8 API functions are available natively

COLORS = {black = 0, dark_blue = 1, dark_purple = 2, dark_green = 3, brown = 4, dark_grey = 5, light_grey = 6, white = 7, red = 8, orange = 9, yellow = 10, green = 11, blue = 12, lavender = 13, pink = 14, light_peach = 15}

-- struct SMap
SMap = {}

-- impl SMap
function SMap:new()
  local obj
  obj = {scroll = -128, scrolling = true}
  setmetatable(obj, {__index = SMap})
  return obj
end
function SMap:stop_scroll()
  self.scrolling = false
end
function SMap:update()
  if not self.scrolling   then
    return
  end
  local last_y = ((128 * 16) - 128)
  if (self.scroll >= last_y)   then
    self.scroll = -256
  end
  self.scroll = (self.scroll + 0.3)
end
function SMap:draw()
  cls(COLORS.dark_grey)
  for i=0,7   do
    local tile_x = (i * 16)
    local map_y = ((i * -256) + self.scroll)
    map(tile_x, 0, 0, map_y, 16, 32)
  end
end

