-- Generated by Rico8
-- Pico-8 API functions are available natively

-- trait Entity
Entity = {}

function Entity:draw(
)
  local sprite = self:get_sprite()
  local x = (flr(self:get_x()) + 0.5)
  local y = (flr(self:get_y()) + 0.5)
  spr(sprite.num, x, y, sprite.w, sprite.h)
end
function Entity:collides_with(
other_x, other_y, other_size)
  local my_x = self:get_x()
  local my_y = self:get_y()
  local my_size = self:get_size()
  return ((((my_x < (other_x + other_size.w)) and ((my_x + my_size.w) > other_x)) and (my_y < (other_y + other_size.h))) and ((my_y + my_size.h) > other_y))
end

-- struct Sprite
Sprite = {}

-- struct Size
Size = {}

-- struct Shooter
Shooter = {}

-- impl Shooter
function Shooter:new(props)
  local obj
  obj = {props = props, last_shot_time = 0}
  setmetatable(obj, {__index = Shooter})
  return obj
end
function Shooter:update(entity_x, entity_y)
  self.last_shot_time = (self.last_shot_time + 0.033)
end
function Shooter:can_shoot()
  return (self.last_shot_time >= self.props.interval)
end
function Shooter:shoot()
  if self:can_shoot()   then
    self.last_shot_time = 0
  end
end
function Shooter:get_bullet_spawn_x(entity_x)
  return (entity_x + self.props.x_offset)
end
function Shooter:get_bullet_spawn_y(entity_y)
  return (entity_y + self.props.y_offset)
end

-- struct BulletProps
BulletProps = {}

-- struct Rotor
Rotor = {}

-- impl Rotor
function Rotor:new(props)
  local obj
  obj = {props = props, angle = 0, entity_x = 0, entity_y = 0}
  setmetatable(obj, {__index = Rotor})
  return obj
end
function Rotor:update(entity_x, entity_y)
  self.entity_x = entity_x
  self.entity_y = entity_y
  self.angle = (self.angle + 0.4)
  if (self.angle > 6.28)   then
    self.angle = (self.angle - 6.28)
  end
end
function Rotor:draw()
  local center_x = (self.entity_x + self.props.x)
  local center_y = (self.entity_y + self.props.y)
  local dx = (cos(self.angle) * self.props.length)
  local dy = (sin(self.angle) * self.props.length)
  line((center_x - dx), (center_y - dy), (center_x + dx), (center_y + dy), 6)
  if (self.props.length > 1.5)   then
    local angle2 = (self.angle + 1.57)
    local dx2 = (cos(angle2) * self.props.length)
    local dy2 = (sin(angle2) * self.props.length)
    line((center_x - dx2), (center_y - dy2), (center_x + dx2), (center_y + dy2), 6)
  end
end

-- struct RotorProps
RotorProps = {}

BUTTON_MASKS = {left = 1, right = 2, up = 4, down = 8, left_up = 5, right_up = 6, left_down = 9, right_down = 10}

-- enum Scene
Start = {
  tag = "Start"
}
Game = {
  tag = "Game"
}
GameOver = {
  tag = "GameOver"
}

-- struct TheLady
TheLady = {}

-- impl TheLady
function TheLady:new()
  local obj
local bullet_props = {x_offset = 0, y_offset = -1, interval = 0.4, sw = 1, sh = 1}
  obj = {x = 63, y = 111, sprite = {num = 1, w = 1, h = 1}, size = {w = 8, h = 8}, shooter = Shooter:new(bullet_props), main_rotor = Rotor:new({x = 4.5, y = 3.5, length = 2}), tail_rotor = Rotor:new({x = 4, y = 7, length = 1}), alive = true}
  setmetatable(obj, {__index = TheLady})
  return obj
end
function TheLady:update(scene)
  local is_game = (function()
    local __match = scene
    if __match.tag == "Game"     then
      return true
    elseif true     then
      return false
        end
  end)()
  local outside = (is_game and self:move_player() or false)
  self.shooter:update(self.x, self.y)
  self.main_rotor:update(self.x, self.y)
  self.tail_rotor:update(self.x, self.y)
  return outside
end
function TheLady:move_player()
  local can_l = (self.x > -1)
  local can_r = ((self.x + self.size.w) < 126)
  local can_u = (self.y > 0)
  local can_d = ((self.y + self.size.h) < 128)
  local can_lu = (can_l and can_u)
  local can_ld = (can_l and can_d)
  local can_ru = (can_r and can_u)
  local can_rd = (can_r and can_d)
  if ((btn(0) and btn(2)) and can_lu)   then
    self.x = (self.x - 1)
    self.y = (self.y - 1)
  else
    if ((btn(1) and btn(2)) and can_ru)     then
      self.x = (self.x + 1)
      self.y = (self.y - 1)
    else
      if ((btn(0) and btn(3)) and can_ld)       then
        self.x = (self.x - 1)
        self.y = (self.y + 1)
      else
        if ((btn(1) and btn(3)) and can_rd)         then
          self.x = (self.x + 1)
          self.y = (self.y + 1)
        else
          if (btn(0) and can_l)           then
            self.x = (self.x - 1)
          else
            if (btn(1) and can_r)             then
              self.x = (self.x + 1)
            else
              if (btn(2) and can_u)               then
                self.y = (self.y - 1)
              else
                if (btn(3) and can_d)                 then
                  self.y = (self.y + 1)
                end
              end
            end
          end
        end
      end
    end
  end
  return ((((self.x < -10) or (self.x > 138)) or (self.y < -10)) or (self.y > 138))
end
function TheLady:get_x()
  return self.x
end
function TheLady:get_y()
  return self.y
end
function TheLady:hit()
  self.alive = false
  sfx(1)
end
function TheLady:is_alive()
  return self.alive
end
function TheLady:get_size()
  return self.size
end

-- impl Entity for TheLady
function TheLady:get_x()
  return self.x
end
function TheLady:get_y()
  return self.y
end
function TheLady:get_sprite()
  return self.sprite
end
function TheLady:get_size()
  return self.size
end
function TheLady:draw()
  if self.alive   then
    palt(256)
    local x = (flr(self.x) + 0.5)
    local y = (flr(self.y) + 0.5)
    spr(self.sprite.num, x, y, self.sprite.w, self.sprite.h)
    palt(32768)
    self.main_rotor:draw()
    self.tail_rotor:draw()
  end
end
-- Copy default methods from Entity
for k, v in pairs(Entity) do
  if TheLady[k] == nil then
    TheLady[k] = v
  end
end

